[providers]
node = true
python = true

[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip", "nodejs_20"]

[phases.install]
cmds = [
    "npm install",
    "pip install --break-system-packages -r bot_reqs.txt"
]

[start]
cmd = "npm start"
